version: '3.1'

services:
  # Nginx container as reverse proxy
  reverseproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - api
    container_name: reverseproxy
    hostname: reverseproxy
    restart: on-failure
    ports:
      - 3000:3000 # HOST:CLIENT
  
  # API container
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    container_name: api
    hostname: api
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres  # Postgres Container name
      - DB_PORT=5432      # Default port : 5432
      - DB_NAME=mainBDD
      - DB_USER=admin
      - DB_PASSWORD=admin
      - REDIS_HOST=redis  # Redis Container name
    restart: on-failure
  
  # Postgres container
  postgres:
    image: postgres
    depends_on:
      - redis
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mainBDD
      PGDATA: /data/postgres
    restart: on-failure
    volumes:
      - pgdata:/data/postgres

  # Redis container
  redis:
    image: redis
    container_name: redis
    restart: on-failure

# Volume for postgres 
volumes:
    pgdata:
        external: true